<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'description'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function dishes()
    {
        return $this->belongsToMany(Dish::class);
    }

    public function parent()
    {
        return Category::where('id', $this->parent_id)->first();
    }

    public function childs() {
        return $this->hasMany(Category::class,'parent_id','id');
    }

    public function isDefault(){
        return $this->user->hasRole('admin');
    }

    public static function allToAccess($with_child = false){
        $results = [];
        if (auth()->user()->hasRole('admin')){
            if(!$with_child){
                $results = Category::where('parent_id', '=', null)
                    ->get();
            }else{
                $results = Category::all();
            }
        }else{
            if(!$with_child) {
                $results = User::getAdmin()
                    ->categories()
                    ->where('parent_id', '=', null)
                    ->get()
                    ->merge(
                        auth()
                            ->user()
                            ->categories()
                            ->where('parent_id', '=', null)
                            ->get()
                    );
            }else{
                $results = User::getAdmin()
                    ->categories
                    ->merge(
                        auth()
                            ->user()
                            ->categories
                    );
            }
        }

        return $results;
    }

    public function delete()
    {
        Category::where('parent_id', $this->id)->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }

}
