<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['name', 'phone', 'email', 'persons', 'street', 'home', 'dop', 'restaurant_id', 'user_id'];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function($order) {
            \DB::table('dishes_orders')->where('order_id', '=', $order->id)->delete();
        });
    }

    public function dishes()
    {
        return $this->belongsToMany(Dish::class, 'dishes_orders', 'order_id', 'dish_id')->withPivot(['quantity', 'price', 'total_price', 'variants']);
    }

    public function restaurant()
    {
        return $this->belongsTo(Restaurant::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }


}
